camera0: 0
camera1: 2
frame_width: 800
frame_height: 600
mono_calibration_frames: 45
stereo_calibration_frames: 45
view_resize: 1
checkerboard_box_size_scale: 4.18
checkerboard_rows: 4
checkerboard_columns: 5
cooldown: 50